//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
[assembly: System.Reflection.AssemblyFileVersion("2.1.117")]
[assembly: System.Reflection.AssemblyVersion("2.1.117")]
=======
[assembly: System.Reflection.AssemblyFileVersion("2.1.118")]
[assembly: System.Reflection.AssemblyVersion("2.1.118")]
>>>>>>> 43f761b5c7249ce0a8a3f4fcc1409c9102c4aaa5


